# Generated by Django 4.1.7 on 2023-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
